// User
GET http://localhost:5000/posts


###
POST http://localhost:5000/posts
Content-Type: application/json

{
  "title": "alan walker",
  "postText": "alan@gmail.com",
  "username": "asdasd"
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
  "name": "mmmmmm Doe",
  "email": "mmmm@gmail.com",
  "gender": "male"
}

###
DELETE http://localhost:5000/users/2

// Book
###
GET http://localhost:5000/books
###

POST http://localhost:5000/books
Content-Type: application/json

{
  "book": "aaaaa",
  "age": "2018",
  "stock": "1"
}

###
POST http://localhost:5000/comments
Content-Type: application/json

{
  "commentBody": "hi",
  "PostId": 1
}
